### ISSUE TITLE
Category weldment assembly

### ISSUE THREAD

**Issue by HelmutMelmer** [koechlm/VDS-Sample-Configurations-2024#1]
Hi Markus,

I found a small error in your C:\ProgramData\Autodesk\Vault 2024\Extensions\DataStandard\CAD.Custom\addinsADSK.QS.Default.ps1. (see image)

[[VDS-Sample-Configurations-2024](https://github.com/koechlm/VDS-Sample-Configurations-2024)](https://github.com/koechlm/VDS-Sample-Configurations-2024/blob/master/VDS-MFG-Sample/CAD.Custom/addins/ADSK.QS.Default.ps1)

kind regards

Helmut Melmer

![14-06-2023_09-27-44](https://github.com/koechlm/VDS-Sample-Configurations-2024/assets/136568759/2ea6c479-55bf-4955-abdb-4e30d612d004)

**Comment by koechlm** [comment]
Thank you for this heads-up, Helmut!
The code base is updated; the next release will include the fix. Also backported it to the 2023 sample configuration.
I very much appreciate your collaboration
